### PR TITLE
Add gitit issues

### PR DESCRIPTION
**Pull request by robertzk**

### CODE REVIEW

**Comment by robertzk** [comment]
@peterhurford Right now, `gitit issues search_query` opens a list of *all* issues matching that query, including closed ones, and not in the order you'd expect (by open-time -- so open and closed issues may be interleaved). Show I add a flag `--all` and by default only list open issues?

**Comment by peterhurford** [comment]
Thanks for this.

The `--all` flag sounds like a good idea.

Can you also add documentation to the `README`?

**Comment by robertzk** [comment]
Will do.

**Comment by iveksl2** [comment]
:+1:

**Comment by peterhurford** [comment]
@robertzk Any plans to finish this PR? ;)

**Comment by robertzk** [comment]
@peterhurford Done.

**Pull request merged**
